### ISSUE TITLE
npm install of bcrypt falls back to source compile every time

### ISSUE THREAD

**Issue by pachoclo** [kelektiv/node.bcrypt.js#473] opened 2017-01-05 14:57 UTC
The url for binaries seems to have changed and makes npm install fallback to source compile every time (this would not be a big deal if there weren't dependencies on python, make, etc, which makes the installation a problem on alpine docker images of node).

I believe the "remote_path" for the binaries in **package.json** should be changed to:

`"remote_path": "kelektiv/node.bcrypt.js/archive/v{version}/"`

(I added a note on the commit that introduced the problem: https://github.com/kelektiv/node.bcrypt.js/commit/27b3b7428523d6cd5126cb7cff02e28d6b605356)

**Comment by klimashkin** [comment] 2017-01-06 09:31
The same thing, after upgrading from 0.8.7 to 1.0.2, I can't build it on linux machine (core 4.5.0) (osx is ok)

<img width="1091" alt="screen shot 2017-01-06 at 1 29 13 am" src="https://cloud.githubusercontent.com/assets/576077/21713621/b3cdfb6c-d3af-11e6-8425-b3e2cf04c823.png">

**Comment by RyanSadowski** [comment] 2017-01-06 18:16
I'm on Arch linux, I was having trouble yesterday but was able to build today. It build successfully on heroku as well. 

I was adding the module for the first time

**Comment by klimashkin** [comment] 2017-01-06 18:25
The problem is that if you upload built application to target server and try to do there `npm rebuild`, it will do nothing with bcrypt now because node-pre-gyp says that binary is already exists. But starting project fails, because brypt should be recompiled.
Removing package and installing it again helps, but falls into compilation from source, because node-pre-gyp can't find precompiled package remotely anyway.

So, really, why we need node-pre-gyp, @defunctzombie? It is compiled from source just find as before 1.0.0 version, but create a lot of question and confusion for developers who use bcrypt.
Moreover, sometimes target server can have blocked access to outside world (like npm registry) for security reasons, and npm can't download package to install it.

**Comment by KManu** [comment] 2017-01-10 12:07
I just tried installing for the first time using npm on windows, and i encounter the same error. However, the problem is that the remote path @pachoclo recommended seems to have no binaries for windows, ie, it hits a 404 when trying to access 
`https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-win32-x64.tar.gz`

**Comment by stewartcelani** [comment] 2017-01-20 04:12
Stuck with same issue here.

**Comment by Agathver** [comment] 2017-01-20 13:59
See #470 will be resolved when that is implemented

**Comment by michelgokan** [comment] 2017-02-17 17:35
I just added this pull request, it fixed my problem: https://github.com/kelektiv/node.bcrypt.js/pull/489

**Comment by defunctzombie** [comment] 2017-02-18 17:14
@klimashkin node-gyp-pre was added largely for windows and (maybe heroku) users who were having issues deploying and working with this project because it required software installed on their machine to build the native bindings. Even tho the readme explicitly says what you need to do, no one reads it or has the experience to deal with binary software compilation. As such, I accepted a PR to enable use of node-gyp-pre (knowing that it does have a fallback to source build if needed) but not realizing the amount of pain in making sure the binary releases are uploaded to github. Sadly I do not see any docs on the readme reminding me of how and where to upload the binaries, so I need to re-learn the process.

**Comment by newdesignideas** [comment] 2017-02-28 06:12
The same thing happens on Mac OS and then node-gyp gets a different error.

**Comment by donaldwasserman** [comment] 2017-03-09 20:46
Does anyone have a interim solution here while waiting on a fix?

**Comment by RyabokonRoman** [comment] 2017-03-13 18:22
This (and a lot of other problems with this terrible package) could be resolved in one short fix (without changing anything more):
![SS](https://dl.dropboxusercontent.com/s/fp27gb52pqwllw3/Screenshot%202017-03-14%2001.19.49.png)
[https://github.com/dcodeIO/bcrypt.js](https://github.com/dcodeIO/bcrypt.js)

**Comment by donaldwasserman** [comment] 2017-03-13 19:29
that's a little harsh.  FWIW, I globally installed node-gyp and node-pre-gyp and then did `npm rebuild` and it seems to be working quite well on ubuntu 16.04

**Comment by defunctzombie** [comment] 2017-03-14 16:21
If you are ok with having your main even loop blocked completely then sure, go for it.

**Comment by kingjerod** [comment] 2017-05-07 23:27
For anybody who is using this package with a Docker node:alpine image, if the base alpine image is version 3.3 or greater there is a virtual flag for apk install which keeps your resulting Docker images small. Make your Dockerfile npm install line look like this:

```
RUN apk --no-cache add --virtual builds-deps build-base python && npm install && apk del builds-deps
```

The `build-deps` is the group name associated with the installed build tools, and it is deleted after the `npm install`. This way only the built npm modules are left on that image layer.

Using this method, I was able to keep the image size at 75 MB. Without using this method and keeping the build tools, the image size was 260 MB. I verified that the bcrypt module installed correctly by running a test hash after building the image.

**Comment by TylerBrock** [comment] 2017-06-06 05:12
What is going on here? @kingjerod's suggestion works but we are boiling the oceans having everyone compile this thing over and over. Lets just fix the link!

**Comment by notbrain** [comment] 2017-07-06 16:55
Would this be fixed by uploading builds for all architectures instead of just Windows on each release page on github? Always 404s for us when looking for `https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.2/bcrypt_lib-v1.0.2-node-v48-darwin-x64.tar.gz` (also Linux). Only Windows builds for various node versions are available as tarballs. Might be above and beyond the the time commitment of maintaners (or the lack of machines to do builds), but that would solve it at the source. 

Thinking of forking and doing custom builds just for our needs, but note forking does not bring over *any* build artifacts *at all*. Downside is responsibility for noticing updates to upstream.

**Comment by Agathver** [comment] 2017-07-06 17:04
@notbrain 
>Would this be fixed by uploading builds for all architectures instead of just Windows on each release page on github?

Yes. However, the number of architectures are enormous, with hundreds of variables. `node-pre-gyp` is mostly for windows where the compilaton steps would be frustrating. Similar arrangements for macs can be made.

However for Linux and BSDs, the situation is very difficult. Varying libc versions and variants add to the problem (glibc in mainstream linux vs musl and friends in Alpine linux). There is no one size fits all solution. And fortunately on a Linux machines installing the build tools are fairly easy.

**Comment by kingjerod** [comment] 2017-07-06 17:35
@Agathver Is this something that could be accomplished using a CI tool? With something like Codefresh, you can specify a docker image to use, then a series of shell commands to execute. I'm not sure what it takes to build that tar file.

**Comment by idchlife** [comment] 2017-08-08 12:25
I'm getting 

```bash
/app/node_modules/bcrypt/lib/binding/bcrypt_lib.node: Exec format error
```

even after using @kingjerod solution.

Right when there is require("brcypt") in my code.

Did anyone experience this problem?

**Comment by agathver** [comment] 2017-08-09 12:26
@idchlife Are you using a alpine-linux based docker ?

**Comment by idchlife** [comment] 2017-08-09 12:31
@agathver I switched to node-alpine from official repository vs https://hub.docker.com/r/mhart/alpine-node/
and error was gone.

**Closed** 2017-08-13 02:26 UTC

**Comment by gbahamondezc** [comment] 2017-09-20 19:26
@idchlife which one is the official repository?

**Comment by gbahamondezc** [comment] 2017-09-20 19:52
@idchlife Ah, you did mean the official node image, thanks. 

Finally it worked for me in **mhart/alpine-node** changing [bcrypt](https://www.npmjs.com/package/bcrypt) by [bcryptjs](https://github.com/dcodeIO/bcrypt.js).

**Comment by myaskevich** [comment] 2017-10-11 12:39
For all those you didn't get it to work after adding `--build-from-source=bcrypt` (or equivalent `rebuild` command after install) - make sure you're not copying your local `node_modules` into the image by adding `.dockerignore` file with contents:

```
node_modules/
```

cc @idchlife

**Comment by core-process** [comment] 2017-11-02 19:45
@agathver `node-pre-gyp` just released a new version, which support the `{libc}` token in the path and package name variables. The token resolves to `glibc` or `musl`.

See:
- https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md#0639
- https://github.com/mapbox/node-pre-gyp/blob/master/README.md#versioning
- Working example: https://github.com/core-process/snapsync/blob/master/node/package.json#L14-L15

**Comment by agathver** [comment] 2017-11-04 16:03
@core-process This will be a great blessing to us!

**Comment by augustovictor** [comment] 2017-11-04 19:41
Thanks @myaskevich .

I just had to add node_modules to my .dockerignore file and everything worked ! =D

**Comment by debadattatabi** [comment] 2018-02-27 18:47
Finally after many research I solve this problem. So, guys those who are facing this problem just do the below processes,

I just installed python and set the environment variables now it's working perfect for me.

Install Python (while installing in windows you can get the option for add path in environment variables, just tick the check box or else)
Set the path in environment variables
Now store the downloaded python.exe file in this directory "c:\Python\27\python.exe"
Now run this cmd in terminal npm config set python "c:\Python\27\python.exe"
Now do npm install or run your project. 
 guys just check it out may be you solve your problem :)

**Comment by diegofreemind** [comment] 2018-07-30 22:34
Hey @RyabokonRoman thanks!
I faced a similar problem and solved with your suggestion replacing by bcryptjs.

**Comment by jzhw0130** [comment] 2019-02-14 01:44
Hey @RyabokonRoman thanks!
Good job!
