### ISSUE TITLE
Pre-built binaries not installable for bcrypt@4.0.1 and node@12.16.3 

### ISSUE THREAD

**Issue by surendra172001** [kelektiv/node.bcrypt.js#797] opened 2020-05-06 05:32 UTC
Thanks for reporting a new issue with the node bcrypt module!

To help you resolve your issue faster please make sure you have done the following:

* Searched existing issues (even closed ones) for your same problem
* Make sure you have installed the required dependencies listed on the readme
* Read your npm error log for lines telling you what failed, usually it is a problem with not having the correct dependencies installed to build the native module

Once you have done the above and are still confident that the issue is with the module, please describe it below. Some things that really help get your issue resolved faster are:

* What went wrong?
* What did you expect to happen?
* Which version of nodejs and OS?
* If you find a bug, please write a failing test.

Thanks!

P.S. If it doesn't look like you read the above then your issue will likely be closed without further explanation. Sorry, but there are just too many issues opened with no useful information or questions which have been previously addressed.

**Comment by savorymaxwell** [comment] 2020-05-06 18:29
Not sure if this will help. But after updating to NPM@6.14.5 and uninstalling and reinstalling Xcode command line tools via https://stackoverflow.com/questions/34617452/how-to-update-xcode-from-command-line I was able to successfully install bcrypt@4.0.1 with Node@12.16.3

**Comment by numToStr** [comment] 2020-05-12 14:29
I am also facing this issue. It fails to download the prebuilt binary. Here are my CI logs.
```
162 | #16 11.20 error /usr/src/app/node_modules/bcrypt: Command failed.
163 | #16 11.20 Exit code: 1
164 | #16 11.20 Command: node-pre-gyp install --fallback-to-build
165 | #16 11.20 Arguments:
166 | #16 11.20 Directory: /usr/src/app/node_modules/bcrypt
167 | #16 11.20 Output:
168 | #16 11.20 node-pre-gyp info it worked if it ends with ok
169 | #16 11.20 node-pre-gyp info using node-pre-gyp@0.14.0
170 | #16 11.20 node-pre-gyp info using node@12.16.3 \| linux \| x64
171 | #16 11.20 node-pre-gyp WARN Using needle for node-pre-gyp https download
172 | #16 11.20 node-pre-gyp info check checked for "/usr/src/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" (not found)
173 | #16 11.20 node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-x64-glibc.tar.gz
174 | #16 11.20 node-pre-gyp http 302 https://github.com/kelektiv/node.bcrypt.js/releases/download/v4.0.1/bcrypt_lib-v4.0.1-napi-v3-linux-x64-glibc.tar.gz
175 | #16 11.20 node-pre-gyp WARN Pre-built binaries not installable for bcrypt@4.0.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
176 | #16 11.20 node-pre-gyp WARN Hit error Remote end closed socket abruptly.
```

**Comment by avillarubia** [comment] 2020-05-18 12:07
@savorymaxwell are you using macos?

**Comment by agathver** [comment] 2020-05-29 10:34
NodeJS updated their OpenSSL library which broke needle which is used to download binaries.

As a workaround, do `npm install request` to let bcrypt use request to download binaries

https://github.com/mapbox/node-pre-gyp/issues/500
https://github.com/tomas/needle/issues/312
https://github.com/nodejs/node/issues/33254

**Comment by agathver** [comment] 2020-05-29 10:36
Closing as duplicate of #796

**Closed by agathver** 2020-05-29 10:36 UTC
