### ISSUE TITLE
[URGENT] Installation failed on production system

### ISSUE THREAD

**Issue by creativenoobie** [kelektiv/node.bcrypt.js#805] opened 2020-05-28 20:01 UTC
* What went wrong?
Unable to install bcrypt
* What did you expect to happen?
To be able to install without failure
* Which version of nodejs and OS?
node@12.16.3 and Ubuntu@18.04

Here's the error log:

> bcrypt@4.0.1 install /home/xmpp/src/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@4.0.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error Remote end closed socket abruptly. 
make: Entering directory '/home/xmpp/src/node_modules/bcrypt/build'
action_after_build.target.mk:6: *** missing separator.  Stop.
make: Leaving directory '/home/xmpp/src/node_modules/bcrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.3.0-53-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /home/xmpp/src/node_modules/bcrypt
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/xmpp/src/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 5.3.0-53-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/xmpp/src/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/xmpp/src/node_modules/bcrypt
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/xmpp/src/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xmpp/.npm/_logs/2020-05-28T19_53_45_131Z-debug.log

I have tried every solution like installing dependencies. Installing requests. None of them is working.
Please help

**Comment by agathver** [comment] 2020-05-29 10:25
There is some issue with node-pre-gyp and needle, please install `request` as dependency while we find a fix for this. It will download and install prebuilt modules.

Could you send the entire npm error log?  This is just a summary and is of not much help in debugging

**Comment by agathver** [comment] 2020-05-29 10:35
NodeJS updated their OpenSSL library which broke needle which is used to download binaries.

As a workaround, do `npm install request` to let bcrypt use request to download binaries

https://github.com/mapbox/node-pre-gyp/issues/500
https://github.com/tomas/needle/issues/312
https://github.com/nodejs/node/issues/33254

**Comment by agathver** [comment] 2020-05-29 10:36
Duplicate of #796

**Closed by agathver** 2020-05-29 10:36 UTC
