### ISSUE TITLE
app is crashing while using bcrypt's async methods

### ISSUE THREAD

**Issue by manishmawat** [kelektiv/node.bcrypt.js#674] opened 2018-11-12 02:02 UTC
app is crashing while using bcrypt package in the app, to test it separately I put the code in a separate file as below.
1) tried to put the constant (10) value in the hash function instead of getting in getSalt function.
2) tried to catch the error in different ways but not getting any error.
3) if I comment the bcrypt function then everything else (if I have anything) working fine in the function.

        const bcrypt = require('bcrypt');
        async function run(){
        const saltValue =await bcrypt.genSalt(10);
        bcrypt.hash('12345',saltValue)
        .then(result => console.log(result))
        .catch(error => console.log(error));
        }
        run();

Version: node : 9.0.0 npm: '5.5.1' "bcrypt": "^3.0.2"
OS: Windows 7.

**Comment by manishmawat** [comment] 2018-11-12 02:15
The app is crashing for asynchronous functions only.
I tried to use synchronous functions and it is working fine.

    const saltValue = bcrypt.genSaltSync(10);
    const hashed = bcrypt.hashSync('12345',saltValue);

**Comment by agathver** [comment] 2018-11-12 09:14
Please give the error message

**Comment by manishmawat** [comment] 2018-11-12 13:00
executing it with node is not giving any output, but nodemon is showing it as app crash.

![bcrypterror](https://user-images.githubusercontent.com/27475666/48348772-438ebc00-e650-11e8-9ccb-a29eee1f39ce.JPG)

And changing it with the synch methods successfully giving the output.
![bcryptsyncsuccess](https://user-images.githubusercontent.com/27475666/48349010-ff4feb80-e650-11e8-9f7e-35dcd701e5d6.JPG)

**Comment by agathver** [comment] 2018-11-12 16:28
Try to run without nodemon and post the error. You may be hitting an unhandled promise rejection error

**Comment by manishmawat** [comment] 2018-11-12 17:42
Without node it is not giving any output:
![bcryptwithnode](https://user-images.githubusercontent.com/27475666/48365227-561ceb80-e678-11e8-8299-622df3dbb64f.JPG)


I wish I had that unhandled promise error but it is not giving anything.
Just to debug it more I tried below code with more edge cases.

    const bcrypt = require('bcrypt');
    async function run(){
        try{
        console.log('beforeTest');
        const saltValue = await bcrypt.genSalt(10);
        const hashed = await bcrypt.hash('12345',saltValue);
        console.log(hashed);
        console.log('test');
    }
    catch(error)
    {
        console.log(error);
    }
    console.log('AfterTest');
    }
    run();

And the output is:

![bcryptdebug](https://user-images.githubusercontent.com/27475666/48365203-430a1b80-e678-11e8-9b31-b3dd31d92fba.JPG)

**Comment by albehery** [comment] 2018-11-14 01:30
i think this is due to using nested async , the first asyn tries to execute the second line 

> bcrypt.hash('12345',saltValue)

 while waiting for 

> const saltValue =await bcrypt.genSalt(10);

to generate the saltValue which is not generated at the execution time  yet and throws the  error

from documentations it may take up to 3 days to generate one hash if using 31 rounds , and in your case which is 10 rounds it generates ~10 hashes/ second and this is considered a long time in computing operations -  genSalt(rounds) is the main operation that takes time

some suggested solutions
- try to generate the salt outside the function - not recommended 
- try to use less rounds (8) which still depends on cpu speed, number of cores and threads and may work for your cpu but fails on a slower ones.
- try to use .then after generating the salt
- user the official methods which assure to generate the salt first before generating the hash 

```
bcrypt.genSalt(saltRounds, function(err, salt) {
    bcrypt.hash(myPlaintextPassword, salt, function(err, hash) {
        // Store hash in your password DB.
    });
});

Technique 2 (auto-gen a salt and hash):
bcrypt.hash(myPlaintextPassword, saltRounds, function(err, hash) {
  // Store hash in your password DB.
});
```

finally , i'm not 100% sure this is true cause i'm not expert but i'm trying to help as i can

thanks

**Comment by AyKarsi** [comment] 2018-11-14 09:22
can confirm the above behaviour on windows 10. both on node 8.9.2 and 10.13.0 using 3.0.2
On linux (suse and ubuntu) it works fine.
Reverting to 3.0.0 works for me at the moment.

**Comment by manishmawat** [comment] 2018-11-17 23:20
@AyKarsi, I have tried on Windows 7 with node 9.0.0 only and it is working only for synchronous methods, not for asynchronous.

**Comment by agathver** [comment] 2018-11-27 07:34
Could you please create a crashdump using DebugDiag? https://blogs.msdn.microsoft.com/chaun/2013/11/12/steps-to-catch-a-simple-crash-dump-of-a-crashing-process/

**Comment by markterence** [comment] 2018-11-28 02:12
Hi, here is the zipped crashdump using DebugDiag. 

https://www.dropbox.com/s/om6aszrmju1bfbo/FullCab_Date__11_28_2018__Time_09_27_33AM_1.cab?dl=0

**Comment by Tech-engine** [comment] 2018-12-02 07:43
For "bcrypt": "^3.0.2",  Upgrading to Node v10 seems to solve the problem.

**Comment by agathver** [comment] 2018-12-02 11:50
Looks like the resurfacing of a similar error for NodeJS in OSX. The ABI compatibility of NodeJS is horrible. I'm still investigating a fix

**Comment by theprometeus** [comment] 2018-12-04 04:31
Having the same problem, using Windows 10 with Node v8.9.4

**Comment by Dandan1314** [comment] 2018-12-26 15:59
same problem, using archlinux with node v8.9.2

**Comment by e-gautier** [comment] 2019-02-24 17:18
This thing keep silently crashing my app.

**Comment by e-gautier** [comment] 2019-02-24 18:04
I mean "silently terminating", because that's the real term, callback simply isn't called.

**Comment by e-gautier** [comment] 2019-02-24 23:02
[use bcryptjs instead](https://www.npmjs.com/package/bcryptjs)

**Comment by agathver** [comment] 2019-03-01 14:18
Should be fixed with new version and using a NodeJS version other than v8.9.x

**Closed by agathver** 2019-03-01 14:18 UTC

**Comment by mijatovicmile** [comment] 2019-03-30 20:50
I had the same issue with Node.js version **8.9.4** and I successfully fixed the issue with installing recommended version of **bcrypt** based on my **Node.js** version

I fixed the issue with **bcrypt@2.0.1** 

**Important note:** Before you install bcrypt, first check version of Node.js on your machine, and based on that, install appropriate version of bcrypt 

![nodeversion](https://user-images.githubusercontent.com/28740895/55281498-93d39580-5335-11e9-87e7-a814a5fc138b.png)

**Comment by agathver** [comment] 2019-03-31 05:20
@mijatovicmile All versions >= 1.0.3 are compatible with NodeJS 8 except v8.9.x that minor version is problematic.

**Comment by gdrbyKo1** [comment] 2021-01-20 12:27
Encountered this today while running inside Docker. In my case this was caused by using `node:lts-slim` during build, and then copying the artifacts over to a `node:lts-alpine`-based image. As these two variants use different libc implementations, native libs built with either may not work with the other.
It's a mistake I've made in my Dockerfile, of course, but I wish I had received at least some hint as to what could be causing this, rather than the Node runtime just terminating like this 😂 (not bcrypt's fault)

**Comment by agonyz** [comment] 2023-08-23 01:51
@gdrbyKo1 Thank you mate, you really saved me there!

I was having the exact same problem and could not figure out was wrong since my nestjs logs inside the docker container did not show anything :D

**Comment by JordiBustos** [comment] 2024-01-26 23:27
I've verified that using bcrypt 5.1.1 with Node.js 21 on Alpine 3.18 leads to a crash without any specific error. However, when I switched to the Node.js 21 slim variant, the issue was resolved.

**Comment by tuannda1503** [comment] 2024-05-22 16:28
> I've run into a similar problem. My NestJS app functions fine locally, but when I moved it to a Docker container and attempted to invoke 'bcrypt' with version 5.1.1, it caused issues. Initially, I was using the '**node:alpine**' image, but after switching to '**node**' everything seems to be working smoothly now.

resolved my same problem. Thanks

**Comment by Jobinjose01** [comment] 2024-07-15 14:42
> I've run into a similar problem. My NestJS app functions fine locally, but when I moved it to a Docker container and attempted to invoke 'bcrypt' with version 5.1.1, it caused issues. Initially, I was using the '**node:alpine**' image, but after switching to '**node**' everything seems to be working smoothly now.

Yes It solved for me also Thanks

**Comment by canegru** [comment] 2024-09-04 13:18
We've experienced the same thing on a NestJs app running on node:alpine 20.x. Switched to a regular node image and everything is working.
