### ISSUE TITLE
bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz

### ISSUE THREAD

**Issue by killboring** [kelektiv/node.bcrypt.js#853] opened 2021-02-03 15:26 UTC
when i use node install node-red on  windows, it reports  error 404 can't get bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz and bcrypt_lib-v3.0.8-node-v83-win32-x64-unknown.tar.gz, but in offical website , the highest version in 3.0.6 and 3.0.8 is 79.i'm mad imiedately. following is shortcut
  
![图片](https://user-images.githubusercontent.com/12019590/106768552-fb1ba880-6676-11eb-9b48-4f32ca436143.png)

**Comment by recrsn** [comment] 2021-02-03 17:28
83 is the Node version. 3.0.x is no longer supported in new Node versions. Please use bcrypt 5.

If node-red comes with bcrypt 3.x please ask them to update.

If updating is out of scope for you follow this: https://github.com/kelektiv/node.bcrypt.js/wiki/Windows-Support

**Comment by killboring** [comment] 2021-02-03 17:31
but how to solve the problem, i want to install node-red, it tells me can't find 83 version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amitosh Swain Mahapatra"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 凌晨1:28
收件人: "kelektiv/node.bcrypt.js"<node.bcrypt.js@noreply.github.com&gt;; 
抄送: "245996779"<245996779@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [kelektiv/node.bcrypt.js] bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz (#853)





 
83 is the Node version. 3.0.x is no longer supported in new Node versions. Please use bcrypt 5.
 
If node-red comes with bcrypt 3.x please ask them to update.
 
If updating is out of scope for you follow this: https://github.com/kelektiv/node.bcrypt.js/wiki/Windows-Support

**Comment by recrsn** [comment] 2021-02-03 18:36
Do npm i bcrypt@latest or follow instructions given in the wiki

**Comment by killboring** [comment] 2021-02-04 02:02
can u send me the missing two jar(bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz、bcrypt_lib-v3.0.8-node-v83-win32-x64-unknown.tar.gz),I just use node-red locally for study.
if i report the problem to node-red, he will solve my problem or not immidately, he will update his version , will last long time.i can't accpt the lost time



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kelektiv/node.bcrypt.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 凌晨2:44
收件人:&nbsp;"kelektiv/node.bcrypt.js"<node.bcrypt.js@noreply.github.com&gt;;
抄送:&nbsp;"245996779"<245996779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kelektiv/node.bcrypt.js] bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz (#853)





 
Do npm i bcrypt@latest or follow instructions given in the wiki

**Comment by recrsn** [comment] 2021-02-04 02:10
I have reported the problem to node-red.

For now you can simply run npm i bcrypt. 

Also, bcrypt is an optional dependency for node-red, so even if installation fails, node-red will work.

**Comment by killboring** [comment] 2021-02-04 02:32
according to the installing interface,I can't skip the step of bcrypt install.
fail to get the two tar.gz, the install process is interpreted forcely
can u give me a install guide or advice without bcrypt, i wann to run node-red to study its function ,it's very important,our team are studying the visual coding solution&nbsp;to solve industrial internet problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kelektiv/node.bcrypt.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 上午10:10
收件人:&nbsp;"kelektiv/node.bcrypt.js"<node.bcrypt.js@noreply.github.com&gt;;
抄送:&nbsp;"245996779"<245996779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kelektiv/node.bcrypt.js] bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz (#853)





 
I have reported the problem to node-red.
 
For now you can simply run npm i bcrypt.
 
Also, bcrypt is an optional dependency for node-red, so even if installation fails, node-red will work.

**Comment by recrsn** [comment] 2021-02-04 02:43
The node-red installation should not stop. 

It will print an error, but it will continue. 

If it stops, the issue is with node-red and not bcrypt. Please raise an issue with them

**Closed by recrsn** 2021-02-04 02:43 UTC

**Comment by killboring** [comment] 2021-02-04 02:56
as you&nbsp;see,the shortcut&nbsp;tells&nbsp;us&nbsp;the&nbsp;installs&nbsp;has&nbsp;interrupt,and&nbsp;the&nbsp;port 1880&nbsp;can't be&nbsp;listenning,how&nbsp;to solve it&nbsp; 






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kelektiv/node.bcrypt.js"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 上午10:44
收件人:&nbsp;"kelektiv/node.bcrypt.js"<node.bcrypt.js@noreply.github.com&gt;;
抄送:&nbsp;"245996779"<245996779@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [kelektiv/node.bcrypt.js] bcrypt_lib-v3.0.6-node-v83-win32-x64-unknown.tar.gz (#853)





 
The node-red installation should not stop.
 
It will print an error, but it will continue.
 
If it stops, the issue is with node-red and not bcrypt. Please raise an issue with them

**Comment by abdennour** [comment] 2024-09-29 03:54
what about the env var `BCRYPT_BINARY_BUILD_PATH`
