### ISSUE TITLE
Bcrypt fails to install on node v 8.12.0

### ISSUE THREAD

**Issue by GerwinBosch** [kelektiv/node.bcrypt.js#650] opened 2018-09-14 12:21 UTC
What went wrong,

Installing bcrypt@3.0.0 on node v 8.12.0 causes an installation error where previous versions (8.11.4) did not.
See snippet below for the install log
```bash
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
make: Entering directory '/home/gerwinb/triply/triply-server/node_modules/bcrypt/build'
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.0 and node@8.12.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
../src/bcrypt.cc: In function ‘void encode_salt(char*, u_int8_t*, char, u_int16_t, u_int8_t)’:
../src/bcrypt.cc:114:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 encode_salt(char *salt, u_int8_t *csalt, char minor, u_int16_t clen, u_int8_t logr)
 ^~~~~~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt.cc: In function ‘void bcrypt(const char*, const char*, char*)’:
../src/bcrypt.cc:147:1: warning: ‘__builtin___snprintf_chk’ output may be truncated before the last format character [-Wformat-truncation=]
 bcrypt(const char *key, const char *salt, char *encrypted)
 ^~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../src/bcrypt.cc:34:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:65:44: note: ‘__builtin___snprintf_chk’ output between 4 and 5 bytes into a destination of size 4
        __bos (__s), __fmt, __va_arg_pack ());
                                            ^
../src/bcrypt.cc: At global scope:
../src/bcrypt.cc:316:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/bcrypt_lib/src/bcrypt.o.d.raw: No such file or directory
 }
 ^
compilation terminated.
bcrypt_lib.target.mk:103: recipe for target 'Release/obj.target/bcrypt_lib/src/bcrypt.o' failed
make: *** [Release/obj.target/bcrypt_lib/src/bcrypt.o] Error 1
make: Leaving directory '/home/gerwinb/triply/triply-server/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/gerwinb/triply/triply-server/node_modules/bcrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/gerwinb/triply/triply-server/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Linux 4.15.0-34-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/gerwinb/triply/triply-server/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/gerwinb/triply/triply-server/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.2
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi' (1)
Traceback (most recent call last):fo lifecycle bcrypt@3.0.0~install: Failed to exec install script
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 502, in gyp_main
    'cwd': os.getcwd(),
OSError: [Errno 2] No such file or directory
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-34-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/gerwinb/triply/triply-server/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /home/gerwinb/triply/triply-server/node_modules/bcrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gulp-debug@4.0.0 requires a peer of gulp@>=4 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-language-service@0.9.9 requires a peer of typescript@>= 2.3.1 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN tslint-microsoft-contrib@5.1.0 requires a peer of typescript@^2.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN @triply/triply-server@2.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@3.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gerwinb/.npm/_logs/2018-09-14T12_06_58_533Z-debug.log
```
Which version and OS:
Node version 1.12.0
OS: Ubuntu 18.04

**Comment by umair321** [comment] 2018-09-17 14:28
Also need resolution

**Comment by AJRdev** [comment] 2018-09-18 09:02
This issue has normally been fix by this PR (https://github.com/kelektiv/node.bcrypt.js/pull/649) but the fix hasn't been released on the npm repo yet.
A release should be done soon with the fix but meanwhile you can link to the branch master of the github repo in your package.json like this : 

`"bcrypt": "https://github.com/kelektiv/node.bcrypt.js.git#master"`

This is of course temporary solution.

**Comment by murbanowicz** [comment] 2018-09-20 09:58
does anybody know about any progress on that?

**Comment by dantn93** [comment] 2018-09-20 10:41
@AJRdev  I cannot install the bcrypt corresponding to your solution.

**Comment by AJRdev** [comment] 2018-09-20 11:40
@dantn93 What do you mean by you can't install it ?
Normally a release on npm should be done tonight so you wan't have to use my solution :)

**Comment by stridentbean** [comment] 2018-09-20 20:28
@AJRdev I also tried to add `"bcrypt": "https://github.com/kelektiv/node.bcrypt.js.git#master"` to my package json without luck. On my mac, which runs node 10.9.0, I have no problems. But, I'm creating a docker solution which uses node 8.12.0 and is still hitting this issue.

Dockerfile
`# specify the node base image with your desired version node:<version>
FROM node:8

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

EXPOSE 3000
CMD [ "npm", "start" ]
`

**Comment by myaskevich** [comment] 2018-09-21 10:39
@stridentbean try remove `--only=production`.

I was pruning non-production packages during my docker build and bcrypt seems to install okay, but the app couldn't find it.

Disabling the pruning worked for me.

**Comment by agathver** [comment] 2018-09-21 12:53
Please try with v3.0.1

**Comment by jagzviruz** [comment] 2018-09-22 06:50
Having the same issue on `MacOS 10.13.6 High Sierra`
I reinstalled `xcode` and accepted the license and have tried globally installing `node-gyp` and `node-pre-gyp`

```
> yarn add bcrypt
error ~/node_modules/bcrypt: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: ~/node_modules/bcrypt
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@8.12.0 | darwin | x64
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "~/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-darwin-x64-unknown.tar.gz
node-pre-gyp http 302 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.1/bcrypt_lib-v3.0.1-node-v57-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.1 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info ok
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.1 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error write EPROTO 140735783670656:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gypgyp  info infospawn  /usr/bin/python
using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '~/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=~/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn /usr/bin/python
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '~/node_modules/bcrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/.node-gyp/8.12.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~/.node-gyp/8.12.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/.node-gyp/8.12.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=~/node_modules/bcrypt',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.12.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
  CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
rm: ./Release/.deps/Release/obj.target/bcrypt_lib/src/blowfish.o.d.raw: No such file or directory
make: *** [Release/obj.target/bcrypt_lib/src/blowfish.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=~/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=~/node_modules/bcrypt/lib/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"
gyp ERR! cwd ~/node_modules/bcrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=~/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=~/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (~/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Darwin 17.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "~/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd ~/node_modules/bcrypt
node-pre-gyp ERR! node -v v8.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=~/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=~/node_modules/bcrypt/lib/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)
  CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
  SOLINK_MODULE(target) Release/bcrypt_lib.node
  COPY ~/node_modules/bcrypt/lib/binding/bcrypt_lib.node
  TOUCH Release/obj.target/action_after_build.stamp
gyp info ok
```

**Comment by GerwinBosch** [comment] 2018-09-24 14:53
@agathver that's fixed my problem, feel free to close this issue.

**Comment by mkgo** [comment] 2018-09-28 21:02
I am also facing the same issue still with "bcrypt": "3.0.1", node 8.12.0 and npm 6.4.1

**Comment by ellipticaldoor** [comment] 2018-10-01 08:53
Same, with yarn works fine

**Comment by mattcarlotta** [comment] 2018-10-04 21:38
Same issue with `bcrypt@3.01` running on Ubuntu 18.04 LTS (`npm@6.4.1`/`node@8.12.0`).

**Comment by jppresents** [comment] 2018-10-06 10:47
+1
Windows 10
node --version: v8.12.0
npm --version: 6.4.1

node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.1 and node@8.12.0 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\dev\web\asm-server\node_modules\bcrypt\build\bcrypt_lib.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error

**Comment by eric-2d** [comment] 2018-10-07 21:03
With Node v8.X.X use bcrypt >= 1.0.3 and < 3.0.0
(source: front page)

**Comment by olback** [comment] 2018-10-16 19:18
Any updates on this?

**Comment by agathver** [comment] 2018-10-18 02:34
It seems that the main issue is `node-pre-gyp` which tries to use `needle` instead of `request` while downloading. `needle` is heavily broken.

However, I'm not able to reproduce the build failures. Source compile should always work if you have python2, make and a c++ compiler. The most likely reason is you are running npm as root (under sudo).  Source compile will fail in such situations.

**Comment by bjornstar** [comment] 2018-10-24 01:50
We're migrating to [bcryptjs](https://www.npmjs.com/package/bcryptjs), zero dependencies, zero installation headaches.

**Comment by bzuillsmith** [comment] 2018-10-30 08:37
We just upgraded to 8.11.4 and 'request' is in our dependencies. Deploying on AWS Elastic Beanstalk. It is failing to build bcrypt. It'll probably be faster for us to move to bcryptjs than to figure out how to get AWS to build this right.

**Comment by jmacdonald01** [comment] 2018-12-13 16:49
@agathver running `npm install --save request` before attempting to install bcrypt fixed this issue for me! Thank you!

**Comment by herlarb** [comment] 2019-01-04 08:13
Currently using  node v8.12 i also had this problem today, fixed with by specifying a specific bcrypt version  
`yarn add bcrypt@3.0.2`
This works for me

**Comment by ibravoh149** [comment] 2019-04-13 21:34
> bcrypt@3.0.2 install /home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.2 and node@11.14.0 (node-v67 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib' 
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/build'
gyp ERR! System Linux 4.15.0-47-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v67"
gyp ERR! cwd /home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt
gyp ERR! node -v v11.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
node-pre-gyp ERR! System Linux 4.15.0-47-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt
node-pre-gyp ERR! node -v v11.14.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v67' (1)
npm WARN @decorators/express@2.3.0 requires a peer of @decorators/di@>=1.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN turing-ecommerce@1.0.0 No description
npm WARN turing-ecommerce@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@3.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@3.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ibrahim/.npm/_logs/2019-04-13T21_30_36_520Z-debug.log

i have been trying to install bcrypt but i keep getting this error. i have also tried the solutions here but non has worked so far

**Comment by agathver** [comment] 2019-04-14 05:51
@ibravoh149
>  node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/home/ibrahim/Desktop/Projects/turing-ecommerce/node_modules/bcrypt/lib'
 
You have folder permission issues (perhaps you tried a sudo npm install sometimes?) run `chown` on node_modules

Also, update bcrypt to v3.0.4 to use pre-compiled modules for NodeJS 11 and up.

**Comment by JEET0291** [comment] 2019-05-19 06:57
I checked node version with nvm and it was also showing stable (v10.11.0).

Finally, I tried.

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
and it worked for me.

**Comment by YasharF** [comment] 2019-08-11 14:39
Is this still an issue? Can this be marked as resolved?

**Comment by ibravoh149** [comment] 2019-08-11 17:19
Please, mark it as resolved. And thanks guys for your support

**Comment by Youssef20000** [comment] 2019-08-25 19:43
If any one still have this problem you can fix it by doing this 
```
npm install -g node-gyp
npm install --g --production windows-build-tools
``` 
or install cmake and gcc on linux by using 
```
sudo apt install cmake gcc -y 
```

**Comment by abdatta** [comment] 2019-10-04 11:12
Upgrading to `bcrypt 3.0.6` solved the issue for me.

**Closed** 2020-02-17 13:01 UTC

**Comment by BortoBoy** [comment] 2020-04-30 19:09
> It seems that the main issue is `node-pre-gyp` which tries to use `needle` instead of `request` while downloading. `needle` is heavily broken.
> 
> However, I'm not able to reproduce the build failures. Source compile should always work if you have python2, make and a c++ compiler. The most likely reason is you are running npm as root (under sudo). Source compile will fail in such situations.
> 
> Manually adding `request` to dependencies causes `node-pre-gyp` to use it, which fixes issues associated with downloading pre-built binaries.

Works for me

**Comment by sjuanati** [comment] 2020-05-01 10:03
In my case (Linux instance at AWS), after executing these commands it finally worked:

```
$ npm install -g node-gyp
$ sudo yum install gcc-c++
```

**Comment by digvijay-r** [comment] 2020-05-07 12:26
Before installing bcrypt install node-gyp in project dependency, This has solved problem on my machine.

`npm install node-gyp`

then

`npm install bcrypt`
