### ISSUE TITLE
3.0.8 pre-built binary works for Node 12.16.2 but not 12.16.3

### ISSUE THREAD

**Issue by wywywywy** [kelektiv/node.bcrypt.js#798] opened 2020-05-13 09:50 UTC
Using the `node:12.16.2-slim` Docker image, the bcrypt@3.0.8 binary get found and installs correctly.

But using the `node:12.16.3-slim` Docker image, for some reasons it complains that the binary is not installable.

This is Linux x64.

```
# npm i bcrypt@3.0.8 --loglevel verbose
...
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@12.16.3 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/root/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp http 302 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.8/bcrypt_lib-v3.0.8-node-v72-linux-x64-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@3.0.8 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp verb command build [ 'rebuild' ]
...
```

**Comment by wywywywy** [comment] 2020-05-13 09:56
Probably a problem with Node itself - https://github.com/nodejs/node/issues/33254

**Comment by Brooooooklyn** [comment] 2020-05-21 03:01
try Try [@node-rs/bcrypt](https://github.com/napi-rs/node-rs/tree/master/packages/bcrypt)

**Comment by agathver** [comment] 2020-05-29 10:34
NodeJS updated their OpenSSL library which broke needle which is used to download binaries.

As a workaround, do `npm install request` to let bcrypt use request to download binaries

https://github.com/mapbox/node-pre-gyp/issues/500
https://github.com/tomas/needle/issues/312
https://github.com/nodejs/node/issues/33254

**Comment by agathver** [comment] 2020-05-29 10:35
Closing as duplicate of #796

**Closed by agathver** 2020-05-29 10:35 UTC
